      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@v1.4.0
        with:
          svn_username: ${{ secrets.SVN_USERNAME }}
          svn_password: ${{ secrets.SVN_PASSWORD }}
          plugin_slug: advanced-clean-master
